version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      python-production:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: pandas
        update-types: [version-update:semver-major]